apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crypto-digging-ingress
  labels:
    app: crypto-digging-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:354317781339:certificate/54ab8b72-fd0a-41da-97df-7885aff9ec63,arn:aws:acm:us-east-1:354317781339:certificate/7f9d9c85-820b-4503-a94a-9a4aa8c73811
spec:
  rules:
    - host: www.crypto-digging.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crypto-digging-fe-svc
                port:
                  number: 80
    - host: crypto-digging-marketplace.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crypto-digging-be-svc
                port:
                  number: 9000