AWSTemplateFormatVersion: 2010-09-09
Description: ---
  This template deploys the infrastructure for the Crypto Digging Marketplace.

Parameters:
  ProjectName:
    Type: String
    Description: Project name that will be prefixed to resource names
  NetworkStackName:
    Type: String
    Description: Name of the network stack
  EKSIAMRoleName:
    Type: String
    Description: Name of the IAM role for EKS
  EKSClusterName:
    Type: String
    Description: Name of the EKS cluster

Resources: 
  # EKS role
  EKSIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Ref EKSIAMRoleName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  # EKS cluster
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      RoleArn: !GetAtt EKSIAMRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
        - !Sub ${NetworkStackName}-EKSSecurityGroup
        SubnetIds:
        - !Sub ${NetworkStackName}-PublicSubnet1Id
        - !Sub ${NetworkStackName}-PublicSubnet2Id
        - !Sub ${NetworkStackName}-PrivateSubnet1Id
        - !Sub ${NetworkStackName}-PrivateSubnet2Id